### PR TITLE
Ported patches to i3 4.12

### PR DESCRIPTION
**Pull request by minad**
Thank you very much for your patches.

I ported the patches to 4.12. It compiles, but it cannot be installed yet on qubes-3.1 dom0 because of libxkbcommon-x11 which cannot be ported easily to f20. You might still want to keep the patches for the future?

Did you try to get your patches into qubes upstream as an official patch? I think it would be a really nice addition to KDE and XFCE for people who prefer tiling wms. 

What kind of tweaks did you do to get i3 running seamlessly in Qubes? I had to add the following to .i3/config

```
exec --no-startup-id qubes-manager
exec --no-startup-id qvm-run --all 'true'
```

The qvm-run is necessary to bring the transient vms to active again after logging off and on again. Also for the status bar, it could be nice to show the active VMs using an i3status script.

### CODE REVIEW

**Comment by SietsevanderMolen** [comment]
Hi! Thanks for your contribution. :-)

The first version I did was for 4.12 also, but I decided to wait until we can use newer Fedora versions in dom0. I will keep your patches around and we'll be able to use them some day in the future. 4.8 is honestly quite old.

I haven't explored getting it upstream, but I'd rather wait a bit until it matures a bit more. Eventually it would be great to get it up there since there are plenty people who want to use Qubes, but for whom a non-tiling window manager is no option.

As for tweaks other than those two you mentioned, very few are necessary for me. I started using the i3-dmenu-desktop launcher that supports .desktop files, so it's easy to start things on different domU's and have bound the printscreen button to a modified version of Laurent Ghigonis's screenshot tool. (https://jrruethe.github.io/blog/2015/09/17/screenshots-in-qubes/) I run a lot of VM's at any given moment, so I'm not really waiting for a script that lists them. :-) I have some things in my i3status, like VPN status from my personal VPN VM, wifi VM IP address and work/eth0 VM IP address. It's probably not the best idea to do this from a security point of view, as you have to communicate with the VM's to get this information out.

**Comment by minad** [comment]
Hi, thx for your answer. I comment later when I am back at the computer. 

Btw I hope it is ok that I asked at the qubes tiling wm issue, it seems the maintainers would like to have it in principle.

Daniel

Am 13. Mai 2016 12:41:15 MESZ, schrieb Sietse van der Molen notifications@github.com:

**Comment by minad** [comment]
Hi,

according to the qubes people the window manager should adhere to the xdg autostart specification to work well. For this I wrote a script which calls all /etc/xdg/autostart/*.desktop files (without ShowOnlyIn).

I would suggest that we collect some configuration snippets and scripts with sane defaults and maybe provide these scripts in the patched i3 package. These are the issues we might want to solve....
- [x] Start `/etc/xdg/autostart/*.desktop`, `~/.config/autostart/*.desktop`
- [ ] Working screenshots (The aforementioned script?)
- [x] Automatic screen locking with i3lock
- [x] i3status.conf with network status (is it a problem to communicate with the net-vm?), number of active qubes, ...?
- [x] Binding of mod-enter to start terminal in currently focused VM?
- [x] Binding of fn-keys for brightness, volume, ... (see https://faq.i3wm.org/question/3747/enabling-multimedia-keys.1.html)
- [ ] Some default workspace assigments, any ideas?
- [ ] Up-to-date documentation

Do you have more ideas?  These things don't have to be resolved quickly. It is more as a list of things to remember if i3 might be included at some point in the qubes installation.

**Comment by minad** [comment]
I put together some scripts here https://github.com/minad/i3-config

**Comment by SietsevanderMolen** [comment]
Excellent suggestions! You're right, we should be pushing this for inclusion. Tiling is
essential to many people's workflow and i3 is the most popular tiling window manager.

In my opinion we should provide only the essentials in the package and use the Qubes wiki to
disseminate information about more specific topics. The closer we are to a clean i3, the easier it
will  be to maintain and keep secure.
- [ ]  Start /etc/xdg/autostart/_.desktop, ~/.config/autostart/_.desktop
  -- I'm not familiar with this part of the standard, but if Marek says so it's probably true. :-)
- [ ]  Working screenshots (The aforementioned script?)
  -- Although we could do this, Qubes doesn't for it's other DE's. You shouldn't normally be able
      to do this as it's a huge security liability.
- [ ]  i3status.conf with network status (is it a problem to communicate with the net-vm?), number of active qubes, ...?
  -- Possible, but it's tricky to generalize. Most power users can set this up themselves if they
      feel the need.
- [ ]  Binding of mod-enter to start terminal in currently focused VM?
  -- Awesome, lets do this.
- [ ]  Binding of fn-keys for brightness, volume, ... (see https://faq.i3wm.org/question/3747/enabling-multimedia-keys.1.html)
  -- Sure, I can share mine. You probably have very similar ones.
- [ ]  Some default workspace assigments, any ideas?
  -- I don't think we should do this, most i3 users have very specific wishes on how to arrange
      their workspaces.
- [ ]  Up-to-date documentation
  -- Absolutely! We should place this in the Qubes documentation and be careful not to
  unnecesarily duplicate any existing i3 documentation. It will probably just be a list of
      Qubes specific tricks.

It's important to try and stick to secure defaults. Installing i3 on Arch Linux and writing tons of
crappy shell scripts to do fancy things is different from providing a solid and secure tiling window
manager for a distribution like Qubes. (That's a note to myself)

**Comment by minad** [comment]
I agree with your argument that we shouldn't impose our workflow onto other people through a too fine grained default configuration. We could provide some niceties commented out or provide example configurations in the wiki,

I just installed qubes + i3 (used i3 before on debian, arch etc). So I would love too see your scripts for inspiration if you are willing to share :)

The mod+enter works more or less, see i3-config/terminal

**Comment by SietsevanderMolen** [comment]
Hi, I started working on the documentation. Here's the relevant file: https://github.com/SietsevanderMolen/qubes-doc/blob/i3-qubes/customization/i3.md. I took everything that seems generalizable enough from your repo and adapted them/made them into gists, hope this is okay with you. Any comments/changes before I create the pull request?

**Comment by minad** [comment]
Cool! I will go over them later and let you know if I have something to add!

Am 22. Mai 2016 14:22:55 MESZ, schrieb Sietse van der Molen notifications@github.com:

**Comment by minad** [comment]
Hi Sietse,

this looks very good. Thx for your work! I like the improved the scripts :)

A few comments:
- Great to know that one can generate json for the statusbar. However I think you can keep it a bit simpler by not always assigning the echoed result to a variable. Take a look at my modified script https://github.com/minad/i3-config/blob/master/status (I also removed a bit of your awesomeness ;)
- I reworked the terminal script a bit and used the i3-sensible-terminal code for the dom0 and the VMs. I think this is better than the terminal variable. What do you think? See https://github.com/minad/i3-config/blob/master/terminal
- I don't like this gist system very much. Maybe keep the example scripts in one repository like i3-qubes-example-config (including all the i3 config files)? You could link to the repository from the documentation. I understand that you don't want to create a default configuration which imposes too much on the user. However as a potential user I would prefer to see all the relevant modified files at one place to get a better overview.
- Maybe don't mention i3status since it doesn't work at all with qubes?
- I think the disclaimer is a bit too strong. You are right about the necessary manual configuration. But what else is missing for full integration?

Daniel

**Comment by SietsevanderMolen** [comment]
- _Great to know that one can generate json for the statusbar. However I think you can keep it a bit simpler by not always assigning the echoed result to a variable. Take a look at my modified script https://github.com/minad/i3-config/blob/master/status (I also removed a bit of your awesomeness ;)_
  
  Nice, even without the awesomeness. :-) I still don't think a measure of active qubes is in any way useful to anybody, what does it tell you? It would be cool to get some more Qubes specific information in there, but it's hard to generalize as everybody has different domains set up.
- _I reworked the terminal script a bit and used the i3-sensible-terminal code for the dom0 and the VMs. I think this is better than the terminal variable. What do you think? See https://github.com/minad/i3-config/blob/master/terminal_
  
  Sure, that's probably a lot faster. The $TERMINAL variable I was checking is actually the first on that list. :-) Lets use your version, I guess people who are specific about their terminals know how to change it anyway/have similar terminals on different qubes. 
- _I don't like this gist system very much. Maybe keep the example scripts in one repository like i3-qubes-example-config (including all the i3 config files)? You could link to the repository from the documentation. I understand that you don't want to create a default configuration which imposes too much on the user. However as a potential user I would prefer to see all the relevant modified files at one place to get a better overview._
  
  As you guessed the reason I chose to make them gists is to underline the fact that they are not ready-to-use one-size-fits-all replacement scripts. If they are, we should be packaging them and place them during install. I agree that we need a place to have an overview of them, but this place would be the Qubes documentation. Really, there are only 3 files that might need changing, depending on what you want to do.
  - The i3 config, which we can't package because it is generated based on keyboard layout (your config doesn't work on my system for example)
  - The xdg autostart stuff,  which could be done anywhere really, even .xinitrc
  - the i3bar thing, which is optional and also highly subject to taste
  
  The terminal thing is nice, but a trick and not really necessary, anything else is too specific and won't be right for many people, in my opinion. I think two/three gists for that should be fine, or any other pastebin really. 
- _Maybe don't mention i3status since it doesn't work at all with qubes?_
  
  i3status works fine with Qubes for me actually. Not all parts of it, but that can be fixed by manually adding them. I chose not to use it just so we can leave out that dependency.
- _I think the disclaimer is a bit too strong. You are right about the necessary manual configuration. But what else is missing for full integration?_
  
  I just took that literally from the XFCE Qubes documentation that I used as a template, you're right. :-)

**Comment by minad** [comment]
One question: What is the advantage of this xfce build system? Is this xfce-specific or is this qubes-xfce-specific? Because without that it also worked fine for me (I mean just the bare patched i3 package definition).

> Nice, even without the awesomeness. :-) I still don't think a measure of active qubes is in any way useful to anybody, what does it tell you? It would be cool to get some more Qubes specific information in there, but it's hard to generalize as everybody has different domains set up.

It is not a very useful, maybe I just like to see it for the fun of it ;)
Getting out further information from other user-defined domains is surely not generalizable, but we can at least rely a bit on the preconfigured domains.

> Sure, that's probably a lot faster. The $TERMINAL variable I was checking is actually the first on that list. :-) Lets use your version, I guess people who are specific about their terminals know how to change it anyway/have similar terminals on different qubes. 

Yes, they will know. And they can also change the list of preferred terminals in run_terminal.

> i3status works fine with Qubes for me actually. Not all parts of it, but that can be fixed by manually adding them. I chose not to use it just so we can leave out that dependency.

I meant that nearly nothing of the information can be used (only date and disk usage?). And since the resource-saving advantage of i3status is gone as soon as you have to get the network information out of the net vm, I thought I better rewrite the complete status script.

**Comment by SietsevanderMolen** [comment]
Maybe I shouldn't have called it a build system, it's just some Makefiles that generalize building a patched package. It's much simpler to use and maintain. Now you can just `make get-sources` and then `make rpms` and you're done. Don't know who wrote it, but I called it XFCE build system because I took it from here: https://github.com/QubesOS/qubes-desktop-linux-xfce4 I thought it would be good to try and mimick that one, instead of relying on a series of commands that I list in my blog.

I will replace the terminal and status scripts with your updated version, go over them one more time and create the pull request.

**Comment by minad** [comment]
Ok. Shouldn't it be sufficient to just call `make rpms` and this does the rest?

**Comment by SietsevanderMolen** [comment]
Now it should. :-) https://github.com/SietsevanderMolen/i3-qubes/commit/f6b28233e1ac09e949a0c4e44b72eef116bc80cd

Also, for reference, here's the pull request: https://github.com/QubesOS/qubes-doc/pull/143

**Comment by marmarek** [comment]
What is status of this? Since Qubes 3.2 have fc23 based dom0, 4.12 should be easy there.

**Comment by minad** [comment]
@marmarek I rebased it on the current qubes-3.1 ("master"). It compiles but it is untested since I don't have a f23 dom0 available.

**Comment by marmarek** [comment]
If you provide me list of things to test (besides basic "does it run"), I can do it.

**Comment by minad** [comment]
Concerning the ported patch (https://github.com/minad/i3-qubes/blob/i3-4.12/i3/0001-Show-qubes-domain-in-non-optional-colored-borders.patch), it is only necessary to check if everything works well with the coloring and the title.

I cannot say exactly what changes in the i3 config and needs testing. But maybe @SietsevanderMolen can?

**Comment by marmarek** [comment]
(for the next time) take a look at https://www.qubes-os.org/doc/code-signing/
We're going to enforce this rule soon (will be announced).

**Comment by minad** [comment]
@marmarek Makes sense :)

**Comment by minad** [comment]
I guess this one can be closed since the patches are already in the qubes repo?

**Pull request closed without merging**
